package br.com.fiap.tds.enun;

public enum CategoriaProduto {
	AUTOS, BEBES_CRIANCAS, BRINQUEDOS, ALIMENTOS_BEBIDAS, CAMA_MESA_BANHO, CASA_SEGURANCA, ELETRODOMESTICOS, ELETROPORTATEIS,
	FERRAMENTAS_JARDIM, MOVEIS,_DECORACAO, PET_SHOP, PRODUTOS_LIPESA, UTILIDADE_DOMESTICAS,
	ESPORTE_LAZER, INSTRUMENTOS_MUSICAIS, PAPELARIA, REVELACAO_DIGITAL, MUSICAS_FILMES_SERIES, LIVROS, BELEZA, VCUIDADOS_SAUDE,
	MALAS_MOCHILAS, MODA, PERFUMARIA_COSMETICOS, RELOGIOS_JOIAS, ACESSÓRIOS, DRONES_CAMERAS, ELETRONIOS, GAMES, INFORMATICA, TABLETS, TELEFONIA
}
